# Site settings
title: "Yibo Luo"
email: luoyibo1@sjtu.edu.cn
description: "Second-year undergraduate student at CSE, Shanghai Jiao Tong University."
url: "https://marslordd.github.io"
baseurl: ""
repository: "Marslordd/Marslordd.github.io"
github_username: Marslordd
minimal_mistakes_skin: default
search: true
timezone: Asia/Shanghai

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

# Outputting
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/

include:
  - _pages

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name: "Yibo Luo"
  avatar: "/assets/images/profile.jpg"
  bio: "Shanghai Jiao Tong University"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Marslordd"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Marslordd"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
